version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ec2-user/dustinbelliston
hooks:
  AfterInstall:
#    - location: scripts/install_dependencies.sh
#      timeout: 3000
#      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root